name: Send Telegram
on: workflow_dispatch

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.CHAT_ID }}
          message: "New Email: ${{ github.event.inputs.email }}, Game: ${{ github.event.inputs.gameTitle }}"
