name: Send Telegram Message

on:
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.CHAT_ID }} \
          -d text="🚀 Test message from GitHub Actions"
